In [61]:
import numpy as np

arr = np.array([
    [
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]
    ],

    [
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]
    ],

    [
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]
    ]
])

print(arr.shape)

(3, 4, 5)


# Section A – Access Individual Elements

In [62]:
print(arr[0,0,0])
print(arr[0,2,4])
print(arr[1,1,2])
print(arr[1,2,3])
print(arr[2,0,4])
print(arr[2,3,1])
print(arr[2,1,3])
print(arr[1,3,4])

10
24
37
43
54
66
58
49


# Section B – Complete Rows

In [63]:
print(arr[0,1])
print(arr[1,2])
print(arr[2,3])

[15 16 17 18 19]
[40 41 42 43 44]
[65 66 67 68 69]


# Section C – Complete Matrices

In [64]:
print(arr[0])

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [65]:
print(arr[1])
print(arr[2])

[[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]]


# Section D – Columns

In [66]:
print(arr[0,:,0])

[10 15 20 25]


In [67]:
print(arr[1,:,2])

[32 37 42 47]


In [68]:
print(arr[2,:,4])

[54 59 64 69]


# Section E – Slicing

In [69]:
print(arr[:2])

[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [70]:
print(arr[1:])

[[[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]


In [71]:
print(arr[:,:2,:])

[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[50 51 52 53 54]
  [55 56 57 58 59]]]


In [72]:
print(arr[:,2:,:])

[[[20 21 22 23 24]
  [25 26 27 28 29]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]

 [[60 61 62 63 64]
  [65 66 67 68 69]]]


In [73]:
print(arr[:,:,:3])

[[[10 11 12]
  [15 16 17]
  [20 21 22]
  [25 26 27]]

 [[30 31 32]
  [35 36 37]
  [40 41 42]
  [45 46 47]]

 [[50 51 52]
  [55 56 57]
  [60 61 62]
  [65 66 67]]]


In [74]:
print(arr[:,:,3:])

[[[13 14]
  [18 19]
  [23 24]
  [28 29]]

 [[33 34]
  [38 39]
  [43 44]
  [48 49]]

 [[53 54]
  [58 59]
  [63 64]
  [68 69]]]


# Section F – Advanced Slicing

In [75]:
arr = np.array([
    [
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]
    ],

    [
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]
    ],

    [
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]
    ]
])

print(arr)

[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]


In [76]:
print(arr[:1,:2,:3])

[[[10 11 12]
  [15 16 17]]]


In [77]:
print(arr[1,2:,2:])

[[42 43 44]
 [47 48 49]]


In [78]:
print(arr[2,1:,:2])

[[55 56]
 [60 61]
 [65 66]]


In [79]:
print(arr[0,:2,3:])

[[13 14]
 [18 19]]


# Section G

In [80]:
print(arr[::2])

[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]


In [81]:
print(arr[:,::2,:])

[[[10 11 12 13 14]
  [20 21 22 23 24]]

 [[30 31 32 33 34]
  [40 41 42 43 44]]

 [[50 51 52 53 54]
  [60 61 62 63 64]]]


In [82]:
print(arr[:,:,::2])

[[[10 12 14]
  [15 17 19]
  [20 22 24]
  [25 27 29]]

 [[30 32 34]
  [35 37 39]
  [40 42 44]
  [45 47 49]]

 [[50 52 54]
  [55 57 59]
  [60 62 64]
  [65 67 69]]]


In [83]:
print(arr[:,:,0])

[[10 15 20 25]
 [30 35 40 45]
 [50 55 60 65]]


In [84]:
print(arr[:,:,-1])

[[14 19 24 29]
 [34 39 44 49]
 [54 59 64 69]]


In [85]:
print(arr[:,2,:])

[[20 21 22 23 24]
 [40 41 42 43 44]
 [60 61 62 63 64]]


In [86]:
print(arr[:,:,2])

[[12 17 22 27]
 [32 37 42 47]
 [52 57 62 67]]


In [87]:
arr[::-1]

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [88]:
arr[:, ::-1, :]

array([[[25, 26, 27, 28, 29],
        [20, 21, 22, 23, 24],
        [15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14]],

       [[45, 46, 47, 48, 49],
        [40, 41, 42, 43, 44],
        [35, 36, 37, 38, 39],
        [30, 31, 32, 33, 34]],

       [[65, 66, 67, 68, 69],
        [60, 61, 62, 63, 64],
        [55, 56, 57, 58, 59],
        [50, 51, 52, 53, 54]]])

In [89]:
arr[:, :, ::-1]

array([[[14, 13, 12, 11, 10],
        [19, 18, 17, 16, 15],
        [24, 23, 22, 21, 20],
        [29, 28, 27, 26, 25]],

       [[34, 33, 32, 31, 30],
        [39, 38, 37, 36, 35],
        [44, 43, 42, 41, 40],
        [49, 48, 47, 46, 45]],

       [[54, 53, 52, 51, 50],
        [59, 58, 57, 56, 55],
        [64, 63, 62, 61, 60],
        [69, 68, 67, 66, 65]]])

# 2D Array

In [90]:
import numpy as np

arr = np.array([
    [10, 11, 12, 13, 14, 15],
    [20, 21, 22, 23, 24, 25],
    [30, 31, 32, 33, 34, 35],
    [40, 41, 42, 43, 44, 45],
    [50, 51, 52, 53, 54, 55],
    [60, 61, 62, 63, 64, 65]
])

print(arr.shape)

(6, 6)


# 2D Array Indexing & Slicing

In [91]:
print(arr[::2])

[[10 11 12 13 14 15]
 [30 31 32 33 34 35]
 [50 51 52 53 54 55]]


In [92]:
print(arr[:,::2])

[[10 12 14]
 [20 22 24]
 [30 32 34]
 [40 42 44]
 [50 52 54]
 [60 62 64]]


In [93]:
print(arr[:,0])

[10 20 30 40 50 60]


In [94]:
print(arr[:,-1])

[15 25 35 45 55 65]


In [95]:
print(arr[3])

[40 41 42 43 44 45]


In [96]:
print(arr[:,3])

[13 23 33 43 53 63]


In [97]:
print(arr[:3])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]]


In [98]:
print(arr[3:])

[[40 41 42 43 44 45]
 [50 51 52 53 54 55]
 [60 61 62 63 64 65]]


In [99]:
print(arr[:,:3])

[[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]
 [50 51 52]
 [60 61 62]]


In [100]:
print(arr[:,3:])

[[13 14 15]
 [23 24 25]
 [33 34 35]
 [43 44 45]
 [53 54 55]
 [63 64 65]]


In [101]:
print(arr[::-1])

[[60 61 62 63 64 65]
 [50 51 52 53 54 55]
 [40 41 42 43 44 45]
 [30 31 32 33 34 35]
 [20 21 22 23 24 25]
 [10 11 12 13 14 15]]


In [102]:
print(arr[:,::-1])

[[15 14 13 12 11 10]
 [25 24 23 22 21 20]
 [35 34 33 32 31 30]
 [45 44 43 42 41 40]
 [55 54 53 52 51 50]
 [65 64 63 62 61 60]]


In [103]:
print(arr[::-1,::-1])

[[65 64 63 62 61 60]
 [55 54 53 52 51 50]
 [45 44 43 42 41 40]
 [35 34 33 32 31 30]
 [25 24 23 22 21 20]
 [15 14 13 12 11 10]]


# Write a single indexing/slicing statement to extract:

In [104]:
print(arr[1:4,2:5])

[[22 23 24]
 [32 33 34]
 [42 43 44]]


In [105]:
print(arr[0::2,1::2])

[[11 13 15]
 [31 33 35]
 [51 53 55]]


In [106]:
print(arr[3:5])

[[40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [107]:
print(arr[:,4:])

[[14 15]
 [24 25]
 [34 35]
 [44 45]
 [54 55]
 [64 65]]
