# Assignment 3 — Tensor Python Tasks

In [1]:
import numpy as np


## Task 1 — Create a Tensor

Create a 1D tensor with the given sensor readings and print its values, shape, dimensions and number of elements.


In [2]:
sensor_readings = np.array([25.2, 25.5, 24.9, 26.1, 25.8])

print("Tensor:", sensor_readings)
print("Shape:", sensor_readings.shape)
print("Number of dimensions:", sensor_readings.ndim)
print("Number of elements:", sensor_readings.size)


Tensor: [25.2 25.5 24.9 26.1 25.8]
Shape: (5,)
Number of dimensions: 1
Number of elements: 5


## Task 2 — From Vector to Matrix

**Answer:** Each row represents one time step and each column represents one sensor.


In [3]:
temperature = [25, 26, 25, 27, 28]
pressure = [101, 102, 101, 103, 104]
humidity = [60, 62, 61, 63, 64]
vibration = [0.2, 0.3, 0.2, 0.4, 0.5]

X = np.array([temperature, pressure, humidity, vibration]).T

print("Tensor:")
print(X)
print("Shape:", X.shape)
print("Number of dimensions:", X.ndim)
print("First time step:", X[0])
print("Temperature readings:", X[:, 0])
print("Vibration readings:", X[:, 3])
print("Axis 0 = time, Axis 1 = sensors")


Tensor:
[[ 25.  101.   60.    0.2]
 [ 26.  102.   62.    0.3]
 [ 25.  101.   61.    0.2]
 [ 27.  103.   63.    0.4]
 [ 28.  104.   64.    0.5]]
Shape: (5, 4)
Number of dimensions: 2
First time step: [ 25.  101.   60.    0.2]
Temperature readings: [25. 26. 25. 27. 28.]
Vibration readings: [0.2 0.3 0.2 0.4 0.5]
Axis 0 = time, Axis 1 = sensors


## Task 3 — Create a 3D Tensor

**Answer:** The tensor has dimensions **Machine × Time × Sensor = (10, 5, 4)**.


In [4]:
# 10 machines × 5 time steps × 4 sensors
X = np.arange(10 * 5 * 4).reshape(10, 5, 4)

print("Shape:", X.shape)

# Machine 3, time step 2 (using Python zero-based indexing)
print("Temperature reading of machine 3 at time step 2:", X[2, 1, 0])

# All sensor readings of machine 5
print("All readings of machine 5:")
print(X[4])

# All machines at time step 1
print("All machines at time step 1:")
print(X[:, 0, :])

# Sensor 4 from all machines and all time steps
print("Sensor 4 readings:")
print(X[:, :, 3])


Shape: (10, 5, 4)
Temperature reading of machine 3 at time step 2: 44
All readings of machine 5:
[[80 81 82 83]
 [84 85 86 87]
 [88 89 90 91]
 [92 93 94 95]
 [96 97 98 99]]
All machines at time step 1:
[[  0   1   2   3]
 [ 20  21  22  23]
 [ 40  41  42  43]
 [ 60  61  62  63]
 [ 80  81  82  83]
 [100 101 102 103]
 [120 121 122 123]
 [140 141 142 143]
 [160 161 162 163]
 [180 181 182 183]]
Sensor 4 readings:
[[  3   7  11  15  19]
 [ 23  27  31  35  39]
 [ 43  47  51  55  59]
 [ 63  67  71  75  79]
 [ 83  87  91  95  99]
 [103 107 111 115 119]
 [123 127 131 135 139]
 [143 147 151 155 159]
 [163 167 171 175 179]
 [183 187 191 195 199]]


## Task 4 — Indexing a Tensor

Given `X = np.arange(24).reshape(2, 3, 4)`:

**Answers:**
1. Shape = **(2, 3, 4)**
2. `X[0]` represents the first block, with shape **(3, 4)**
3. `X[0,0]` represents the first row of the first block, with shape **(4,)**
4. `X[0,0,0]` represents one scalar element.


In [5]:
X = np.arange(24).reshape(2, 3, 4)

print("X:")
print(X)
print("\nX[0]:")
print(X[0])
print("\nX[1]:")
print(X[1])
print("\nX[0, 0]:")
print(X[0, 0])
print("\nX[0, 0, 0]:")
print(X[0, 0, 0])

print("\nShape:", X.shape)
print("Shape of X[0]:", X[0].shape)
print("Shape of X[0,0]:", X[0,0].shape)
print("X[0,0,0] is a scalar:", np.isscalar(X[0,0,0]))


X:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

X[0]:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

X[1]:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

X[0, 0]:
[0 1 2 3]

X[0, 0, 0]:
0

Shape: (2, 3, 4)
Shape of X[0]: (3, 4)
Shape of X[0,0]: (4,)
X[0,0,0] is a scalar: True


## Task 5 — Slicing

The required slices are:
- First block: `X[0]`
- First row from every block: `X[:, 0, :]`
- Third element from every row and block: `X[:, :, 2]`
- Last two elements: `X[:, :, -2:]`


In [6]:
X = np.arange(60).reshape(3, 4, 5)

first_block = X[0]
first_row_every_block = X[:, 0, :]
third_element_every_row_block = X[:, :, 2]
last_two_elements = X[:, :, -2:]

print("First block:")
print(first_block)
print("Shape:", first_block.shape)

print("\nFirst row from every block:")
print(first_row_every_block)
print("Shape:", first_row_every_block.shape)

print("\nThird element from every row and block:")
print(third_element_every_row_block)
print("Shape:", third_element_every_row_block.shape)

print("\nLast two elements:")
print(last_two_elements)
print("Shape:", last_two_elements.shape)


First block:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Shape: (4, 5)

First row from every block:
[[ 0  1  2  3  4]
 [20 21 22 23 24]
 [40 41 42 43 44]]
Shape: (3, 5)

Third element from every row and block:
[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]
Shape: (3, 4)

Last two elements:
[[[ 3  4]
  [ 8  9]
  [13 14]
  [18 19]]

 [[23 24]
  [28 29]
  [33 34]
  [38 39]]

 [[43 44]
  [48 49]
  [53 54]
  [58 59]]]
Shape: (3, 4, 2)


## Task 6 — Image Tensor

Create an RGB image tensor with shape **(128, 128, 3)**. Pixel values are generated randomly from 0–255.


In [7]:
image = np.random.randint(0, 256, size=(128, 128, 3), dtype=np.uint8)

red = image[:, :, 0]
green = image[:, :, 1]
blue = image[:, :, 2]

print("Image shape:", image.shape)
print("Red channel shape:", red.shape)
print("Green channel shape:", green.shape)
print("Blue channel shape:", blue.shape)
print("Maximum pixel value:", image.max())
print("Minimum pixel value:", image.min())


Image shape: (128, 128, 3)
Red channel shape: (128, 128)
Green channel shape: (128, 128)
Blue channel shape: (128, 128)
Maximum pixel value: 255
Minimum pixel value: 0


## Task 7 — Batch of Images

Create 32 RGB images of size 128 × 128.


In [8]:
images = np.random.randint(0, 256, size=(32, 128, 128, 3), dtype=np.uint8)

first_image = images[0]
first_10_images = images[:10]
red_all_images = images[:, :, :, 0]
pixel_50_50 = images[:, 50, 50, :]

print("Batch shape:", images.shape)
print("First image shape:", first_image.shape)
print("First 10 images shape:", first_10_images.shape)
print("Red channel from all images shape:", red_all_images.shape)
print("Pixel (50,50) from every image shape:", pixel_50_50.shape)


Batch shape: (32, 128, 128, 3)
First image shape: (128, 128, 3)
First 10 images shape: (10, 128, 128, 3)
Red channel from all images shape: (32, 128, 128)
Pixel (50,50) from every image shape: (32, 3)


## Task 8 — Reshape

**Answer:** Reshaping changes how the same elements are arranged across dimensions. It does not change the total number of elements, so every target shape must have a product of dimensions equal to 24.


In [9]:
X = np.arange(24)

shapes = [(4, 6), (2, 3, 4), (6, 4), (24,)]

for shape in shapes:
    reshaped = X.reshape(shape)
    print("\nShape:", reshaped.shape)
    print("Dimensions:", reshaped.ndim)
    print(reshaped)

print("\nTotal elements:", X.size)



Shape: (4, 6)
Dimensions: 2
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Shape: (2, 3, 4)
Dimensions: 3
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Shape: (6, 4)
Dimensions: 2
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Shape: (24,)
Dimensions: 1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Total elements: 24


## Task 9 — Reshape vs Transpose

**Answer:** No. `reshape()` changes the arrangement of elements into a new shape, while `transpose()` changes the order of axes. They can produce different values even when the resulting shapes are the same.


In [10]:
X = np.arange(24).reshape(2, 3, 4)

reshaped = X.reshape(3, 2, 4)
transposed = X.transpose(1, 0, 2)

print("Original:")
print(X)

print("\nReshape (3,2,4):")
print(reshaped)

print("\nTranspose (1,0,2):")
print(transposed)

print("\nAre they equal?", np.array_equal(reshaped, transposed))


Original:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Reshape (3,2,4):
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

Transpose (1,0,2):
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

Are they equal? False


## Task 10 — Broadcasting

**Answer:** A `(4,)` array is compatible with `(3,4)` because NumPy aligns dimensions from the right. The 4 elements are applied independently to each of the 3 rows.


In [11]:
X = np.ones((3, 4))
b = np.array([10, 20, 30, 40])

print("X + b:")
print(X + b)

print("\nX * b:")
print(X * b)


X + b:
[[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]

X * b:
[[10. 20. 30. 40.]
 [10. 20. 30. 40.]
 [10. 20. 30. 40.]]


## Task 11 — Broadcasting with Sensor Data

The calibration vector has shape `(10,)`, so NumPy broadcasts it across all 100 samples.


In [12]:
X = np.random.randn(100, 10)

calibration = np.array([
    1.2, 0.8, 1.1, 0.5, 0.9,
    1.0, 0.7, 1.3, 0.6, 0.4
])

calibrated_X = X - calibration

print("Original shape:", X.shape)
print("Calibration shape:", calibration.shape)
print("Calibrated shape:", calibrated_X.shape)


Original shape: (100, 10)
Calibration shape: (10,)
Calibrated shape: (100, 10)


## Task 12 — Tensor Aggregation

For `X.shape = (100, 20, 5)`:
- Mean across time → **(100, 5)**
- Mean across sensors → **(100, 20)**
- Mean across machines → **(20, 5)**
- Maximum across time → **(100, 5)**
- Standard deviation across time → **(100, 5)**


In [13]:
X = np.random.randn(100, 20, 5)

mean_time = X.mean(axis=1)
mean_sensors = X.mean(axis=2)
mean_machines = X.mean(axis=0)
max_time = X.max(axis=1)
std_time = X.std(axis=1)

print("Mean across time:", mean_time.shape)
print("Mean across sensors:", mean_sensors.shape)
print("Mean across machines:", mean_machines.shape)
print("Maximum across time:", max_time.shape)
print("Standard deviation across time:", std_time.shape)


Mean across time: (100, 5)
Mean across sensors: (100, 20)
Mean across machines: (20, 5)
Maximum across time: (100, 5)
Standard deviation across time: (100, 5)


## Task 13 — Normalize a Tensor

**Answer:** Normalize each sensor using its mean and standard deviation calculated over machines and time steps.

Formula:

`X_normalized = (X - mean) / std`


In [14]:
X = np.random.randn(100, 20, 5)

# Mean/std for each sensor: keep sensor axis and reduce machine/time axes
mean = X.mean(axis=(0, 1), keepdims=True)
std = X.std(axis=(0, 1), keepdims=True)

X_normalized = (X - mean) / std

print("Normalized shape:", X_normalized.shape)
print("Mean of each sensor after normalization:")
print(X_normalized.mean(axis=(0, 1)))
print("\nStandard deviation of each sensor after normalization:")
print(X_normalized.std(axis=(0, 1)))


Normalized shape: (100, 20, 5)
Mean of each sensor after normalization:
[-6.65995037e-17  4.44089210e-18  2.61179967e-17  5.62605518e-17
 -1.34198208e-17]

Standard deviation of each sensor after normalization:
[1. 1. 1. 1. 1.]


## Task 14 — Flattening

An image `(28,28,3)` contains `28×28×3 = 2352` values.

For a batch, flatten only the image dimensions and preserve the batch dimension, giving `(64,2352)`.

**Answer:** Flattening the whole batch into `(150528,)` would remove the information about which pixels belong to which image.


In [15]:
image = np.random.rand(28, 28, 3)
flattened_image = image.reshape(2352)

batch = np.random.rand(64, 28, 28, 3)
flattened_batch = batch.reshape(64, 2352)

print("Image shape:", image.shape)
print("Flattened image shape:", flattened_image.shape)
print("Batch shape:", batch.shape)
print("Flattened batch shape:", flattened_batch.shape)


Image shape: (28, 28, 3)
Flattened image shape: (2352,)
Batch shape: (64, 28, 28, 3)
Flattened batch shape: (64, 2352)


## Task 15 — Concatenation

**Answer:** The two tensors have the same batch dimension (32), so they can be concatenated along the feature axis. The feature dimensions 128 and 64 become 192.


In [16]:
visual_features = np.random.randn(32, 128)
sensor_features = np.random.randn(32, 64)

combined_features = np.concatenate(
    [visual_features, sensor_features],
    axis=1
)

print("Visual features:", visual_features.shape)
print("Sensor features:", sensor_features.shape)
print("Combined features:", combined_features.shape)


Visual features: (32, 128)
Sensor features: (32, 64)
Combined features: (32, 192)


## Task 16 — Practical Mini Challenge: Sensor Dataset

Create a tensor with shape **(500, 60, 8)** representing:

**Machines × Time × Sensors**


In [17]:
X = np.random.randn(500, 60, 8)

# 1. Machine 10
machine_10 = X[9]

# 2. First 20 time steps
first_20_time_steps = X[:, :20, :]

# 3. Sensor 5 from all machines
sensor_5 = X[:, :, 4]

# 4. Average value of every sensor
average_each_sensor = X.mean(axis=(0, 1))

# 5. Average value at every time step
average_each_time_step = X.mean(axis=(0, 2))

# 6. Machine with highest average sensor reading
machine_average = X.mean(axis=(1, 2))
highest_machine = np.argmax(machine_average) + 1

# 7. Normalize each sensor
sensor_mean = X.mean(axis=(0, 1), keepdims=True)
sensor_std = X.std(axis=(0, 1), keepdims=True)
X_normalized = (X - sensor_mean) / sensor_std

# 8. Split into training and testing
X_train = X[:400]
X_test = X[400:]

print("Original shape:", X.shape)
print("Machine 10 shape:", machine_10.shape)
print("First 20 time steps shape:", first_20_time_steps.shape)
print("Sensor 5 shape:", sensor_5.shape)
print("Average of every sensor:", average_each_sensor)
print("Average at every time step shape:", average_each_time_step.shape)
print("Machine with highest average reading:", highest_machine)
print("Normalized shape:", X_normalized.shape)
print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)


Original shape: (500, 60, 8)
Machine 10 shape: (60, 8)
First 20 time steps shape: (500, 20, 8)
Sensor 5 shape: (500, 60)
Average of every sensor: [-0.00731082  0.00467585  0.00173884 -0.00400819  0.0014821  -0.00306308
  0.01405533  0.00767358]
Average at every time step shape: (60,)
Machine with highest average reading: 107
Normalized shape: (500, 60, 8)
Training shape: (400, 60, 8)
Testing shape: (100, 60, 8)


## Task 17 — PyTorch

For `torch.arange(24).reshape(2,3,4)`:
- Shape = `(2,3,4)`
- Number of dimensions = `3`
- Number of elements = `24`

For `torch.randn(32,100,768)`, a common interpretation is:

**32 = batch size, 100 = sequence length/time steps, 768 = feature or embedding dimension.**


In [18]:
import torch

X = torch.arange(24).reshape(2, 3, 4)

print(X)
print("Shape:", X.shape)
print("Number of dimensions:", X.ndim)
print("Number of elements:", X.numel())

X = torch.randn(32, 100, 768)

print("\nSecond tensor shape:", X.shape)
print("Possible interpretation:")
print("32  -> batch size")
print("100 -> sequence length / time steps")
print("768 -> feature or embedding dimension")


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
Shape: torch.Size([2, 3, 4])
Number of dimensions: 3
Number of elements: 24

Second tensor shape: torch.Size([32, 100, 768])
Possible interpretation:
32  -> batch size
100 -> sequence length / time steps
768 -> feature or embedding dimension
